# Generated by Django 5.0.13 on 2025-03-16 04:47
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
